### ISSUE TITLE
wasmtime-py was moved

### ISSUE THREAD

**Issue by developerworks** [MediosZ/component-model-demo#1]
Moved from [https://github.com/bytecodealliance/wit-bindgen](https://github.com/bytecodealliance/wit-bindgen) to [https://github.com/bytecodealliance/wasmtime-py](https://github.com/bytecodealliance/wasmtime-py)

https://github.com/bytecodealliance/wit-bindgen/commit/a6d3e3efbfb7240234023773fead49f24f0d007b

**Comment by MediosZ** [comment]
Oh, thanks for telling me this!
I will update the code and the blog soon!

**Comment by MediosZ** [comment]
Close as #2 is merged.
