### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by huwaireb** [MediosZ/component-model-demo#3]
Hi, thought I'd give you a heads up as to the status of the demo.

It has unfortunately became outdated as of recently, It's expected I guess due tot he nature of component-models being a phase 1 proposal.

I've forked the demo and it has the necessary fixes to get it building again.

You can view it here (excluding the python host) (OUTDATED): 
https://github.com/r-muhairi/component-model-demo

Side Note:
Here's the reason why I changed the wit file so that the markdown world became an interface as opposed to a world and introducing a new world called renderer:

It seems i couldn't export a function directly? It wasn't generating an export macro doing this

```typescript
default world markdown {
  export render: func(markdown: string) -> string
}
```

**Comment by cpetig** [comment]
Well, wit-bindgen really seems to be fast evolving, I just updated your changes at https://github.com/cpetig/component-model-demo (although @r-muhairi 's version still compiles due to locking to a specific git version of wit-bindgen)

**Comment by MediosZ** [comment]
I update the code, now it should work like a real demo again
